name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-left.svg
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: >- 
            html, css
          plugin_languages_details: bytes-size, percentage
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-right.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, developer,
            scripter, explorer, infographile
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          token: ${{ secrets.METRICS_TOKEN }}
